#=================================================
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com (chinese)
#=================================================
name: Docker images shotcut

on:
  workflow_dispatch:
#  push:
#    branches:
#      - @master
#    paths:
#      - 'shotcut/*'
  schedule:
    - cron: '39 2 * * 5'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      uses: docker/login-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@master
      with:
        context: .
        platforms: |
          linux/amd64
        file: shotcut/Dockerfile
        push: true
        secrets: |
          "github_token=${{ secrets.GITHUB_TOKEN }}"
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/shotcut:latest

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@main
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/shotcut
        readme-filepath: shotcut/README.md
